Добавил категорию "Автомобилисты" #WF-80
Yandex-Weather-SHRI/yandex.weather-frontend pull request #50
Opened 2017-09-02 17:42 UTC by vbifonixor

https://weather.myjetbrains.com/youtrack/issue/WF-80

2017-09-02 18:47 UTC, artmaks approved these changes

2017-09-02 18:47 UTC, yarastqt approved these changes

2017-09-02 18:49 UTC, artmaks commented
Не мерджить до понедельника

2017-09-02 18:49 UTC, artmaks requested changes
Не мерджить до понедельника

2017-09-04 12:51 UTC, artmaks approved these changes

2017-09-04 12:55 UTC, merged